name: Release PyPi Version

on:
  release:
    types:
      - published

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/underground
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install Dependencies
        run: |
          pip install pip==24.*
          pip install twine==4.* build==1.*

      - name: Build Distribution
        run: python -m build

      - name: Publish Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
