name: Release PyPi Version

on:
  release:
    types:
      - published

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/underground
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-3.10-${{ hashFiles('setup.py') }}

      - name: Install Dependencies
        run: |
          pip install pip==23.*
          pip install twine==4.* build==1.*

      - name: Build Distribution
        run: python -m build

      - name: Publish Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
